### PR TITLE
Logon history

### PR DESCRIPTION
**Pull request by JustATechie**

### CODE REVIEW

**Comment by JustATechie** [comment]
Tested on my own system. Will deploy in testing to STAR Lab machines once replication link has been updated to main branch's version.

**Review by Romey-RomeZ — APPROVED** [review]
Looks good to me

**Comment by mcarras8** [comment]
@JustATechie 
`function setupCheck {
    # If the log folder path does not exist, create it!
    If(-Not (Test-Path -Path $folderPath)) {
        New-Item -Path "C:\Windows\Logs\" -Name "USS-LogonHistory" -ItemType "directory"
    }
`
You reference $folderPath here, but use a hardcoded path instead. Also, I don't think "C:\Windows\Logs\USS-LogonHistory" would be writable to anyone but us (the folder isn't writable by Users on my system, at least).

I'd also recommend making the $from and $to variables script parameters. Makes it a little easier to reuse the code.

**Comment by JustATechie** [comment]
@mcarras8 I've updated the to and from variables to be optional parameters.

I was trying to find a relatively hidden place where I could store the logfiles and script so that standard users wouldn't be poking around too much. I figured "C:\Windows\Logs" was a good candidate since it's meant for logs anyways. The created "USS-LogonHistory" doesn't need to be writeable by standard users since the script is executed via GPO.

**Comment by mcarras8** [comment]
@JustATechie 
From my experience, GPOs running under the Users context runs under that user's account, so it should have their permissions.

**Comment by JustATechie** [comment]
@mcarras8 I've updated the folder path to be directly in C:\ so that it's user read/writeable.

**Pull request merged**
